### ISSUE TITLE
how to generate maze maps?

### ISSUE THREAD

**Issue by jing-4369** [CognitiveAISystems/pogema#2]
hi!
can you please tell how to generate maze maps usign this library,
i just see how to generate random maps.

**Comment by Tviskaron** [comment]
hi! 

You can find mazes map generator in [pogema-toolbox](https://github.com/Tviskaron/pogema-toolbox/blob/main/pogema_toolbox/generators/maze_generator.py)

After generating the map, you can load it into POGEMA by specifying it in the map field of grid_config.

**Comment by jing-4369** [comment]
thanks!
I found it.
