### ISSUE TITLE
Question about collision_system

### ISSUE THREAD

**Issue by shufujian** [CognitiveAISystems/pogema#4]
My MAPF scenario allows follow conflict：
a1: { location: [1, 1] }, a2: { location: [1, 2]}
a1 -> [1,2], a2 -> [1, 3].

To satisfy this requirement, I set collision_system='soft'.

But I found the actions will be corrected when occur collisions, and all actions will be reversed.

I would like to ask whether there is a collision_system that can satisfy both follow conflict and collision without affecting the execution of other normal agents.

much thanks!

**Comment by shufujian** [comment]
Now i just check the actions to check the collicion.

**Comment by aandreychuk** [comment]
I didn't quite get which situation you cannot get via the existing collison system?
With collision_system='soft' such follow actions are allowed => there will be no collision => none of these actions will be reversed. Moreover, any collision_system in pogema affects only colliding actions.

**Comment by shufujian** [comment]
> I didn't quite get which situation you cannot get via the existing collison system? With collision_system='soft' such follow actions are allowed => there will be no collision => none of these actions will be reversed. Moreover, any collision_system in pogema affects only colliding actions.

Oh, it was my fault!
I did not update the locations of agents!

Now, i through checking the locations of agents to check wheather there are collison!

Thanks a lot!
