### ISSUE TITLE
Map with row no and col no is different

### ISSUE THREAD

**Issue by linhlt-it-ee** [CognitiveAISystems/pogema#5]
Hello, can you pls tell  me what is the meaning of the 'size': hyper parameter

**Comment by Tviskaron** [comment]
The ‘size’ hyperparameter specifies the dimensions of the randomly generated map. If you provide a custom map, the ‘size’ parameter will be adjusted automatically. In this case, the width and height can be different.

**Comment by Tviskaron** [comment]
look for example in https://github.com/CognitiveAISystems/MAPF-GPT/issues/4
